import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppSidebar from "@/components/layout/AppSidebar";
import Providers from "./providers";
import { Toaster } from "sonner";
import ThemeInitializer from "@/components/ThemeInitializer";
import I18nInitializer from "@/components/I18nInitializer";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata = {
  title: "Runic",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col md:flex-row">
        <Providers>
          <AppSidebar />
          <main className="flex-1 min-w-0">
            <I18nInitializer />
            <ThemeInitializer />
            {children}
            <Toaster />
          </main>
        </Providers>
      </body>
    </html>
  );
}